services:
  discovery-server:
    image: eclipse-temurin:21-jre-jammy
    volumes:
      - ./infra/discovery-server/target/discovery-server-0.0.1-SNAPSHOT.jar:/app.jar:ro
    command: java -jar /app.jar
    restart: on-failure
    ports:
      - "8761:8761"

  config-server:
    image: eclipse-temurin:21-jre-jammy
    volumes:
      - ./infra/config-server/target/config-server-0.0.1-SNAPSHOT.jar:/app.jar:ro
    command: java -jar /app.jar
    restart: on-failure
    depends_on:
      - discovery-server
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=config-server

  gateway-server:
    image: eclipse-temurin:21-jre-jammy
    volumes:
      - ./infra/gateway-server/target/gateway-server-0.0.1-SNAPSHOT.jar:/app.jar:ro
    command: java -jar /app.jar
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - ewm-service
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=gateway-server

  stats-server:
    build:
      context: stats
      dockerfile: Dockerfile
    container_name: ewm-stats-service
    restart: on-failure
    depends_on:
      config-server:
        condition: service_started
      stats-db:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=stats-server
      - SPRING_DATASOURCE_URL=${STATS_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${STATS_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${STATS_DB_PASSWORD}

  stats-db:
    image: postgres:16.1
    container_name: stats-postgres
    restart: on-failure
    ports:
      - "${STATS_DB_HOST_PORT}:${STATS_DB_CONTAINER_PORT}"
    environment:
      - POSTGRES_PASSWORD=${STATS_POSTGRES_PASSWORD}
      - POSTGRES_USER=${STATS_POSTGRES_USER}
      - POSTGRES_DB=${STATS_POSTGRES_DB}
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build:
      context: core/main-service
      dockerfile: Dockerfile
    container_name: ewm-main-service
    restart: on-failure
    depends_on:
      config-server:
        condition: service_started
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_started
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=ewm-service
      - SPRING_DATASOURCE_URL=${EWM_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${EWM_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${EWM_DB_PASSWORD}

  ewm-db:
    image: postgres:16.1
    container_name: main-postgres
    restart: on-failure
    ports:
      - "${EWM_DB_HOST_PORT}:${EWM_DB_CONTAINER_PORT}"
    environment:
      - POSTGRES_PASSWORD=${EWM_POSTGRES_PASSWORD}
      - POSTGRES_USER=${EWM_POSTGRES_USER}
      - POSTGRES_DB=${EWM_POSTGRES_DB}
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
